// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBrwag4_8CltVF772IGGOvFlul9zHv-Ao',
    appId: '1:131796129875:web:d46f5d6c8fc1b67571cea6',
    messagingSenderId: '131796129875',
    projectId: 'yarachesu-brewcrew',
    authDomain: 'yarachesu-brewcrew.firebaseapp.com',
    storageBucket: 'yarachesu-brewcrew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDBpq2l7Ba1ihd-ByBT698eb5qGf1hemk',
    appId: '1:131796129875:android:e88aa4b14257395471cea6',
    messagingSenderId: '131796129875',
    projectId: 'yarachesu-brewcrew',
    storageBucket: 'yarachesu-brewcrew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgyWl5hnKhIPiGkVMlAxxmoy_MbivpHj8',
    appId: '1:131796129875:ios:46bd5b6a24da36d071cea6',
    messagingSenderId: '131796129875',
    projectId: 'yarachesu-brewcrew',
    storageBucket: 'yarachesu-brewcrew.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgyWl5hnKhIPiGkVMlAxxmoy_MbivpHj8',
    appId: '1:131796129875:ios:01a6ec2f0f69e3e171cea6',
    messagingSenderId: '131796129875',
    projectId: 'yarachesu-brewcrew',
    storageBucket: 'yarachesu-brewcrew.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
